### ISSUE TITLE
Could you add a LICENSE in the repo?

### ISSUE THREAD

**Issue by zhoufengfan** [zhongyy/Face-Transformer#25]
Thanks a lot.

**Comment by zhongyy** [comment]
> Thanks a lot.

I am not familiar with the license…I am sorry If it brings any inconvenience to you or somebody else.

**Comment by zhoufengfan** [comment]
Could you permit us to use the code in the repo for non-commercial purposes?

**Comment by zhongyy** [comment]
> Could you permit us to use the code in the repo for non-commercial purposes?

Sure. I have added the license. Please cite the paper if you use it.

**Comment by zhoufengfan** [comment]
Thanks.
