### ISSUE TITLE
Issues about input normalization

### ISSUE THREAD

**Issue by zcy8123878** [zhongyy/Face-Transformer#8]
Hi, 

I have some questions about your input normalization. Specifically, I checked your code and notice that you leave out normalization for input images which means the input value is ranged [0, 255]. I tried to normalize the input to [-1, 1], and the results dropped a little, so is this a training trick or there is some insights behind it?

**Comment by zhongyy** [comment]
Hi,

Yes, I also try normalize into to [-1,1], and find similar conclusion as yours. I am not sure whether this is a trick.

**Comment by zcy8123878** [comment]
Thanks a lot, your work really do me a great favour
